<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>R&eacute;sum&eacute; - Deep Toaster</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="/lib/fonts/flaticon.css" type="text/css" rel="stylesheet" />
		<link href="https://fonts.googleapis.com/css?family=Raleway:800|Titillium+Web:400,700" type="text/css" rel="stylesheet" />
		<link href="/lib/css/resume.css" type="text/css" rel="stylesheet" />
	</head>
	<body>
		<div id="sidebar">
			<h1>Will Yu</h1>
			<h2>Software engineer, game developer, and graphic designer with a knack for <strong>creative, efficient solutions</strong> to novel problems.</h2>
			<h2>Fast learner, team player, and <strong>detail-oriented problem solver</strong> who likes to have fun and works well under pressure.</h2>
			<h3>Languages</h3>
			<div class="column">
				<p>English</p>
			</div>
			<div class="column">
				<div class="progress">
					<span style="width: 100%;"></span>
				</div>
			</div>
			<div class="column">
				<p>Chinese</p>
			</div>
			<div class="column">
				<div class="progress">
					<span style="width: 100%;"></span>
				</div>
			</div>
			<div class="column">
				<p>French</p>
			</div>
			<div class="column">
				<div class="progress">
					<span style="width: 80%;"></span>
				</div>
			</div>
			<div class="column">
				<p>Spanish</p>
			</div>
			<div class="column">
				<div class="progress">
					<span style="width: 50%;"></span>
				</div>
			</div>
			<h3>Hobbies</h3>
			<table>
				<tr>
					<td>
						<i class="flaticon-people"></i>
					</td>
					<td>
						<i class="flaticon-technology"></i>
					</td>
					<td>
						<i class="flaticon-sports"></i>
					</td>
				</tr>
				<tr>
					<td>
						<i class="flaticon-fountain-pen-close-up"></i>
					</td>
					<td>
						<i class="flaticon-match"></i>
					</td>
					<td>
						<i class="flaticon-drawing"></i>
					</td>
				</tr>
			</table>
			<cite>Font generated by <a href="http://www.flaticon.com/">flaticon.com</a>.</cite>
			<cite>Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a href="http://www.flaticon.com/authors/freepik">Freepik</a></cite>
			<h3>Contact</h3>
			<p>
				<i class="flaticon-telephone-of-old-design"></i>
				<a href="tel:+15034278483">(503) 427-8483</a>
			</p>
			<p>
				<i class="flaticon-note"></i>
				<a href="mailto:yizhenwilliam@gmail.com">yizhenwilliam@gmail.com</a>
			</p>
			<p>
				<i class="flaticon-square"></i>
				<a href="https://www.facebook.com/yizhenwilliam">fb.com/yizhenwilliam</a>
			</p>
			<p>
				<i class="flaticon-link"></i>
				<a href="http://squiffl.es/">squiffl.es</a>
			</p>
			<p>
				<i class="flaticon-multimedia"></i>
				<a href="http://https://github.com/DThought">github.com/DThought</a>
			</p>
		</div>
		<div id="main">
			<h1>Experience</h1>
			<dl>
				<dt>2016</dt>
				<dd>
					<h4>Software Development Intern</h4>
					<h3>Facebook</h3>
					<p>Developed new client-facing interfaces, internal tools, and external developers APIs</p>
				</dd>
				<dt>2015</dt>
				<dd>
					<h4>Software Development Intern</h4>
					<h3>TigerText</h3>
					<p>Developed client-facing administration panels, features for web interface, and toolchain improvements</p>
				</dd>
				<dt>2014</dt>
				<dd>
					<h4>IMSS Representative</h4>
					<h3>Caltech</h3>
					<p>Built and maintained as sysadmin a large RAID 60 server and developed web, mail, and other services</p>
				</dd>
				<dt>2013</dt>
				<dd>
					<h4>Software Development Intern</h4>
					<h3>Intel</h3>
					<p>Developed UX tracking library and analysis tool and improved internal tools</p>
				</dd>
				<dt>2012</dt>
				<dd>
					<h4>Web Designer, Web App Developer</h4>
					<h3>[Freelance]</h3>
				</dd>
			</dl>
			<h1>Education</h1>
			<dl>
				<dt>2017</dt>
				<dd>
					<h4>Computer Science, Aerospace (minor)</h4>
					<h3>Caltech</h3>
					<p>Completed tracks in Graphics and Machine Learning</p>
				</dd>
			</dl>
			<h1>Skills</h1>
			<div class="column">
				<div>
					<h3>Things I Do Well</h3>
					<ul>
						<li>
							<span>General software development</span>
							<span>
								<em>C</em>
								<em>C++</em>
								<em>C#</em>
								<em>Java</em>
							</span>
							<span>
								<em>Haskell</em>
								<em>Lisp</em>
								<em>Lua</em>
								<em>Python</em>
							</span>
						</li>
						<li>
							<span>Full-stack web development</span>
							<span>
								<em>Apache</em>
								<em>nginx</em>
								<em>Node.js</em>
								<em>PHP</em>
							</span>
							<span>
								<em>CSS3</em>
								<em>HTML5</em>
								<em>JavaScript</em>
							</span>
							<span>
								<em>Angular</em>
								<em>jQuery</em>
								<em>Knockout</em>
								<em>React</em>
							</span>
						</li>
						<li>
							<span>Database design and management</span>
						</li>
						<li>
							<span>System administration and security</span>
						</li>
						<li>
							<span>Graphic design and image manipulation</span>
						</li>
					</ul>
				</div>
			</div>
			<div class="column">
				<div>
					<h3>Things I've Made</h3>
					<ul>
						<li>
							<span>Crazy things on a TI-83 Plus</span>
							<ul>
								<li>Fruit Ninja with keypad swipe</li>
								<li>Raycasting and physics engines</li>
							</ul>
						</li>
						<li>
							<span>Online IDEs and in-the-cloud compilers</span>
						</li>
						<li>
							<span>Virtual reality finger painting app</span>
						</li>
					</ul>
					<h3>Awards and Honors</h3>
					<ul>
						<li>
							<span>Featured on The Verge</span>
						</li>
						<li>
							<span>Program of the Year, ticalc.org</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>
